version: '3'

services:
  api:
    build: ./api
    ports:
      - "9721:5000"
    volumes:
      - ./api:/app
    restart: always

  frontend:
    build: ./frontend
    ports:
      - "9720:80"
    depends_on:
      - api
    restart: always