version: '3'

services:
  api:
    build: ./api
    ports:
      - "9721:5000"
    volumes:
      - ./api:/app
      - ./feed:/app/feed  # Persistent storage for camera images
    environment:
      - CAMERA_IP=${CAMERA_IP}  # Set from host environment or .env file
      - CAMERA_PASSWORD=${CAMERA_PASSWORD}  # Set from host environment or .env file
    restart: always

  frontend:
    build: ./frontend
    ports:
      - "9720:80"
    depends_on:
      - api
    restart: always
